<?php
require_once __DIR__.'/initialize.php';

mfwServerEnv::setEnv('unittest');

/**
 * Test class for mfwApplication.
 * Generated by PHPUnit on 2012-12-24 at 15:15:19.
 */
class mfwApplicationTest extends PHPUnit_Framework_TestCase
{
	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
	}

	/**
	 */
	public function testTitle()
	{
		$title = mfwApplication::title();
		$this->assertEquals('unit test',$title);
	}

	/**
	 */
	public function testIdentifier()
	{
		$identifier = mfwApplication::identifier();
		$this->assertEquals('unittest',$identifier);
	}

	/**
	 * @depends testIdentifier
	 */
	public function testCachePrefix()
	{
		$identifier = mfwApplication::identifier();
		$env = 'unittest';
		$dirname = basename(APP_ROOT);

		$prefix = mfwApplication::cachePrefix();
		$this->assertEquals("{$env}_{$identifier}_{$dirname}_",$prefix);
	}
}
?>
