<?php
// you need set 'apc.enable_cli=1' on php.ini
//require_once 'PHPUnit/Framework.php';

require_once __DIR__.'/initialize.php';

class TestApc extends mfwApc {
	public static function makeKey($key){
		return parent::makeKey($key);
	}
}

/**
 * Test class for mfwApc.
 * Generated by PHPUnit on 2013-01-09 at 00:31:39.
 */
class mfwApcTest extends PHPUnit_Framework_TestCase
{
	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		mfwServerEnv::setEnv('unittest');
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
	}

	/**
	 */
	public function testMakeKey()
	{
		$key = TestApc::makeKey('abcdefg');
		$this->assertStringStartsWith(mfwServerEnv::cachePrefix(),$key);
	}

	/**
	 */
	public function testDefaultExpire()
	{
		$def = mfwApc::defaultExpire();
		$this->assertEquals(0,$def);

		$new = mfwApc::defaultExpire(30);
		$this->assertEquals(30,$new);

		$new2 = mfwApc::defaultExpire();
		$this->assertEquals(30,$new2);

		$new3 = mfwApc::defaultExpire(0);
		$this->assertEquals(0,$new3);

		$new4 = mfwApc::defaultExpire();
		$this->assertEquals(0,$new4);
	}

	/**
	 */
	public function testSetGet()
	{
		$key = 'asdfgh';
		$value = 'zxcvb';

		mfwApc::set($key,$value);
		$ret = mfwApc::get($key);

		$this->assertEquals($value,$ret);
	}

	/**
	 * @depends testSetGet
	 */
	public function testDelete()
	{
		$key = 'qwerty';
		mfwApc::set($key,1234567);

		mfwApc::delete($key);
		$this->assertFalse(mfwApc::get($key));
	}

	/**
	 * @depends testSetGet
	 */
	public function testDeletePrefixMatch()
	{
		$key1 = 'zaq1xsw2-1';
		$key2 = 'zaq1xsw2-2';
		$key3 = 'zaq1xs-1';

		mfwApc::set($key1,$key1);
		mfwApc::set($key2,$key2);
		mfwApc::set($key3,$key3);

		mfwApc::deletePrefixMatch('zaq1xsw2');

		$this->assertFalse(mfwApc::get($key1));
		$this->assertFalse(mfwApc::get($key2));
		$this->assertEquals($key3,mfwApc::get($key3));
	}
}
?>
