<?php
require_once __DIR__.'/initialize.php';

/**
 * Test class for mfwSession.
 * Generated by PHPUnit on 2013-01-09 at 00:40:12.
 */
class mfwSessionTest extends PHPUnit_Framework_TestCase
{
	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
	}

	/**
	 */
	public function testSessionStart()
	{
		mfwSession::init();
		$sesname = session_name();
		$exp = mfwServerEnv::cachePrefix().'seskey';
		$this->assertEquals($exp,$sesname);
	}

	/**
	 */
	public function testSetGet()
	{
		mfwSession::set('testkey_set','set');
		$got = mfwSession::get('testkey_set');
		$this->assertEquals('set',$got);
	}

	/**
	 * @depends testSetGet
	 */
	public function testHasKey()
	{
		mfwSession::set('testkey_haskey','haskey');
		$has = mfwSession::hasKey('testkey_haskey');
		$this->assertTrue($has);
	}

	/**
	 * @depends testSetGet
	 * @depends testHasKey
	 */
	public function testClear()
	{
		$_SESSION['dummy_prefix']['value'] = true;
		mfwSession::set('testkey_clear','value');
		mfwSession::clear('testkey_clear');
		$this->assertFalse(mfwSession::hasKey('testkey_clear'));
		$this->assertTrue(isset($_SESSION['dummy_prefix']['value']));
	}

	/**
	 * @depends testSetGet
	 * @depends testHasKey
	 */
	public function testClearAll()
	{
		mfwSession::set('testkey_clearall1','value1');
		mfwSession::set('testkey_clearall2','value2');
		$_SESSION['dummy_prefix']['value'] = true;

		mfwSession::clearAll();
		$this->assertFalse(mfwSession::hasKey('testkey_clearall1'));
		$this->assertFalse(mfwSession::hasKey('testkey_clearall2'));
		$this->assertTrue(isset($_SESSION['dummy_prefix']['value']));

	}
}
?>
